### PR TITLE
2 New options - Dir ignore Prefix and Ignore Sort

### PR DESCRIPTION
**Pull request by seltix5**
Option Dir ignore Prefix :
to be able to use, for example, the prefix "_" in included files.

Option ignore sort :
to be able to manually set the include order

### CODE REVIEW

**Comment by hugabor** [comment]
This looks good to me. (Perhaps 'ignore prefix' might need to be renamed to something like 'ignore path' or 'ignore directory' or something?)

But, if you update the documentation in the README, I'll merge.

Thanks for the contribution and for dealing with my code mess! :D

**Comment by seltix5** [comment]
Hi there!
I'm the one who thank you because your npm was very helpful for me. I needed a command to compile my JS with includes (like Scss does)  and yours was the only one I could find and I'm very glad I did =)
About the ignore prefix, I taught it was the more obvious name because :
 the 'dir' part is because the option is only used with 'dir' option
 The 'ignore-prefix' is for starting chars like '_' so it is not a file nor a directory but a part of the filename. Maybe 'dir-ignore-fileprefix'? 
What you think? Or just 'ignore-fileprefix'?

This is the first time I work on a npm project so I not good at it but I'm a php/Javascript programmer myself so I can handle a bit of Javascript and it was a pleasure to help =)

**Comment by seltix5** [comment]
are you there?

**Comment by hugabor** [comment]
Sorry for the delay.

I am closing this pull-request for now because I have rewritten a lot of the code.
And I think that even though I didn't implement your specific feature request, it is possible to do what you wanted to do.

Instead of having the ability to manually set the concatenation order programmatically, you can now use a new directive `// include` which let's you include the file directly at the location of the comment. This way, you can have a completely custom order just be rearranging your `// include` statements (perhaps in an extra "wrapper" file or "bundling entry point" file.

(As for the "ignore prefix" option, it is no longer possible to include an entire directory - you have to specify an entry file. However, when/if the directory feature gets re-added, we may have to revisit this option.)

Let me know if you have any questions.

**Pull request closed without merging**
